version: "3.8"

services:
  db:
    image: mysql
    container_name: db_budget_buddy
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_budget_buddy
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker/php
    container_name: www_budget_buddy
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: